frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/components/Demo.js, frontend/src/components/EnergyComponent.js, frontend/src/components/Home.js, frontend/src/index.js, frontend/src/theme.js
Luotu aloitussivu ja demosivu, joiden välillä voi liikkua. Demosivun sisältö on tarkoitus korvata UI-suunnitelman mukaisella sisällöllä (päänäkymä, kello ja säästöt). Lisätty theme.js -tiedoston pohja, johon voi myöhemmin lisätä mm. käytettäviä värejä ja fontteja. Luotu (tyhjä) tiedosto EnergyComponent, joka tulee kuvaamaan yksittäistä energiakomponenttia kuten aurinkopaneelia tai sähköautoa.
=> created files for home page, demo page, energy component and theme

frontend/src/components/Clock.jsx, frontend/src/components/Demo.jsx
24 tunnin kello, joka juoksee koko ajan.
=> running clock implemented

backend/package-lock.json, frontend/src/components/Clock.jsx
Lisätty painike, jolla keskeyttää ja jatkaa demon aikaa.
=> Button to pause the time

frontend/src/components/Clock.jsx
Lisätty demoajan nopeuden muuttaminen.
=> Changing demo time speed implemented

frontend/package-lock.json, frontend/src/components/Clock.jsx
Related to Clock. A very miniscule change; mostly for testing everything works correctly in the branch system now.
=> Fixed zero not showing before realtime units below 10

frontend/package-lock.json, frontend/src/components/Clock.jsx
Lisätty mahdollisuus vaihtaa demon aloitusaikaa ja uudelleen aloittaa aika reset painikkeesta.
=> Starting time and reset button

README.md, frontend/package.json, package.json
Npm startin voi nyt ajaa pääkansiosta. Lisätty skriptiin myös backendin npm install.
=> added start script to the main folder & modified readme file

frontend/src/components/Clock.jsx, frontend/src/components/Demo.jsx
Muutettu kellon rakennetta ja pieniä tyylimuutoksia
=> Fix Clock component structure

README.md, frontend/package.json, package.json
Lisätty npm test skripti pääkansioon, joka suorittaa yksikkötestit ja tulostaa testikattavuuden.
=> Add test script to the main folder, modify test script & update readme

frontend/package-lock.json, frontend/package.json, frontend/src/components/Demo.jsx, frontend/src/components/DemoClock.jsx, frontend/src/components/ElectricityPrice.jsx
Lisätty demoajan perusteella päivittyvä hinta päänäkymään. Hinta näytetään kahden desimaalin tarkkuudella.
=> Add current price to main view

frontend/src/components/ComponentMenu.jsx, frontend/src/components/Demo.jsx, frontend/src/components/DemoClock.jsx, package-lock.json
Lisätty komponenttivalikko, jossa toistaiseksi muutama esimerkkikomponentti. Lisäksi muutettu reset painikkeen nimi restartiksi ja poistettu sivun alalaidasta turha restart painike.
=> Component menu

frontend/package-lock.json, frontend/package.json, frontend/src/components/ComponentMenu.jsx, frontend/src/tests/Demo.test.js, frontend/src/tests/DemoClock.test.js, frontend/src/tests/EnergyComponentPage.test.js, frontend/src/tests/Welcome.test.js
Korjattu vanhat yksikkötestit ja lisätty uusia.
=> Update existing unit tests, add more unit tests

backend/src/fetchElectricityPrice.js, frontend/package-lock.json
Hakee puuttuvan historiadatan ja ennustaa, että puuttuvat tulevat hinnat vastaavat edellisen vuorokauden hintoja. Sisältää tehtävät LIQ-75 ja LIQ-76.
TODO-asteella vielä virhetilanteiden hallinta, teen siitä erillisen tehtävän Jiraan.
=> LIQ-75 Fetch & forecast missing prices

frontend/src/components/Demo.jsx, frontend/src/tests/Demo.test.js
Lisätty demosivulle more information -nappi, josta aukeaa dialogi jossa ohjeita ja tieto demossa käytetyn datan alkuperästä.
=> added instructions/info dialog to the demo page

frontend/src/components/Demo.jsx, frontend/src/components/EnergyComponent.jsx, frontend/src/components/Instructions.jsx, frontend/src/components/visual_components/ElectricCar1.jsx, frontend/src/components/visual_components/HeatPump.jsx, frontend/src/components/visual_components/SolarPanel1.jsx, test_data/energyComponents.json
Lisätty komponentin tietojen näyttäminen ilmalämpöpumpun lisäksi myös yhdelle aurinkopaneelille ja sähköautolle. Nämä eriytetty toisteisuuden välttämiseksi omiksi komponenteikseen visual_components kansioon jotta itse demokomponentti pysyisi siistinä, tarkoitus on tehdä sama muillekin komponenteille sitten kun niille on testidataa saatavilla. Muutettu komponenttien id:t (myös testidataan) olemaan random numeroiden sijasta komponenttien nimiä kuvaavia.
=> View component info

frontend/src/components/Demo.jsx, frontend/src/components/DemoClock.jsx, frontend/src/components/EnergyComponentPage.jsx, frontend/src/components/Instructions.jsx, frontend/src/components/Welcome.jsx
Nappien ulkonäkö muokattu ja etusivulle tehty pieniä muutoksia, kuten reunojen pyöristämistä jne.
=> Updated buttons 

frontend/src/components/Demo.jsx, frontend/src/components/EnergyComponent.jsx, frontend/src/components/EnergyComponentPage.jsx
Laatikoiden ulkoasu muokattu rautalankakuvien kaltaiseksi niin päänäkymässä, kuin komponenttien omilla sivuillakin. Samalla komponenttivalikon käytettävyyttä parannettu niin, että valintoja pystyy klikkaamaan valintaruudun lisäksi myös tekstin kohdalta.
=> updating component menu and boxes

frontend/src/App.jsx, frontend/src/components/Demo.jsx, frontend/src/components/EnergyComponent.jsx, frontend/src/components/EnergyComponentPage.jsx, frontend/src/components/NotFound.jsx
Korjattu seuraavat asiat:
- sähkötaulu näyttää taas tuoton oikein
- lisätty not found -sivu, jonne käyttäjä ohjataan jos yrittää mennä sivulle jota ei ole olemassa (eli kirjoittaa osoitepalkkiin osoitteen, joka ei johda mihinkään, näin tapahtuu myös jos kirjoittaa olemassa olevan energiakomponentin osoitteen, koska navigointi toimii vain klikkaamalla komponenttia)
- selaimen takaisin -nappi toimii nyt niin, että demosivulta ohjataan tervetuloa-sivulle ja komponenttien sivuilta demosivulle
=> Fix broken electricboard

frontend/src/components/Demo.jsx, frontend/src/components/ElectricityPrice.jsx, frontend/src/components/EnergyComponent.jsx, frontend/src/components/EnergyComponentPage.jsx, frontend/src/components/Instructions.jsx, frontend/src/components/visual_components/ElectricBoard.jsx
Muutoksia:
- Piilotetut komponentit poistuvat kokonaiskulutuksesta
- Sähkötaulu-komponentin sanamuotoja muutettu ilmaisemaan selkeämmin, että kyse on talon ulkopuolelta tulevasta sähköstä. En tiedä onko se vieläkään ihan selkeästi/oikein muotoiltu, saa ehdottaa jos keksii miten asian ilmaisisi paremmin
- Laatikoiden kokoja säädetty hieman
- Lisätty koko demon kokonaiskulutus päänäkymään
- Ohjetekstiä päivitetty
=> Remove hidden components from total consumption

frontend/src/components/Demo.jsx, frontend/src/components/DemoClock.jsx, frontend/src/components/ElectricityPrice.jsx, frontend/src/components/EnergyComponentPage.jsx, frontend/src/components/Instructions.jsx, frontend/src/components/Welcome.jsx
Lisätty painike, joka poistaa komponenttivalikosta kaikkien komponenttien valinnan. Lisäksi painikkeisiin lisätty isot alkukirjaimet.
=> Added button to clear all components from menu

frontend/src/components/Demo.jsx, frontend/src/components/EnergyComponentPage.jsx, frontend/src/components/Welcome.jsx
Logo lisätty jokaiselle sivulle ja demokuvan reunat pyöristetty.
=> Added the logo on every view and rounded the images

frontend/src/components/Demo.jsx, frontend/src/components/DemoClock.jsx, frontend/src/components/EnergyComponentPage.jsx, frontend/src/components/Welcome.jsx, frontend/src/components/visual_components/ElectricCar1.jsx, frontend/src/components/visual_components/ElectricCar2.jsx, frontend/src/components/visual_components/SolarPanel1.jsx, frontend/src/components/visual_components/SolarPanel2.jsx, frontend/src/components/visual_components/SolarPanel3.jsx, frontend/src/components/visual_components/SolarPanel4.jsx
Kellon nopeusvalinta säilyy ja oletusnopeus on 1 hour / sec. Lisäksi muutin painikkeiden paikan samalla vaivalla eli painikkeet siirretty ylös. Muitakin pieniä säätöjä visuaaliseen näkymään tehty, jotta näkymä asettuisi sitten lopullisessa versiossa ilman tarvetta vierittää sivua. Time laatikosta poistettu Time "otsikko" (tuntui turhalta).
=> Clock fixed and buttons position changed

frontend/src/components/Demo.jsx, frontend/src/components/EnergyComponent.jsx, frontend/src/components/EnergyComponentPage.jsx, frontend/src/components/visual_components/ElectricCar1.jsx, frontend/src/components/visual_components/ElectricCar2.jsx, frontend/src/components/visual_components/Freezer.jsx, frontend/src/components/visual_components/HeatPump.jsx, frontend/src/components/visual_components/Heater.jsx, frontend/src/components/visual_components/HotWaterHeater.jsx, frontend/src/components/visual_components/Jacuzzi.jsx, frontend/src/components/visual_components/Stove.jsx, frontend/src/components/visual_components/WashingMachine.jsx
Kuluttavien komponenttien sivuilla on nyt samassa kaaviossa näkyvissä todellinen kulutus, optimoitu kulutus halvimman sähkön hinnan mukaan (kokonaiskulutuksen ja yksittäisen tunnin maksimikulutuksen pysyessä samana). Lisätty myös kulutetun sähkön hinta ja optimoimalla saadut säästöt näkyviin. (Kokonaishinta ja optimoimalla saadut säästöt voisi myös ehkä lisätä päänäkymään?). Jostain syystä sivun päivitys komponentin sivulla hajottaa jotain (kaikki data ei säily muistissa ja se ilmeisesti aiheuttaa ongelmia).
=> Added optimization for consuming components

backend/index.js, backend/src/fetchElectricityPrice.js
Lisäsin paremman virheiden käsittelyn backendiin. Lisätty myös jokaiselle hinnalle ajan lisäksi tyyppi, joka voi olla joko `api`, `forecasted` tai `fixed`. Api-hinnat on oikeita pörssisähköhintoja, forecasted-hinnat on "ennustettu" eilisen päivän hintojen mukaan ja fixed-hinnat ovat kiinteitä 5 sentin tuntihintoja. Kiinteä hinta asetetaan vain virhetilanteissa, kun apiin ei saada yhteyttä.
=> Add better error handling for backend

backend/package.json, frontend/package.json, frontend/src/components/ElectricityPrice.jsx, frontend/src/components/EnergyComponentPage.jsx, frontend/src/components/Instructions.jsx, frontend/src/components/NotFound.jsx, frontend/src/components/Welcome.jsx, package-lock.json, package.json
Muutamia pieniä korjauksia:
- käynnistysskripti muutettu järkevämpään muotoon
- sähkön hinta -kuvaajan aika-akselille lisätty selitteet ja kuvaajan otsikkoa muutettu
- komponentin sivulla kuvaajan hintayksikkö muutettu cents -> cents (kWh) 
- ohjesivua päivitetty ja mm. fonttikokoa hieman pienennetty
- Not found -sivun painikkeeseen korjattu iso alkukirjain
- Welcome -sivulla jonkun elementin borderRadius-määrittely oli kahteen kertaan niin poistin niistä toisen
=> fixed start script & some other small improvements

frontend/src/components/Demo.jsx, frontend/src/components/EnergyComponentPage.jsx, frontend/src/components/visual_components/ElectricBoard.jsx, frontend/src/components/visual_components/ElectricCar1.jsx, frontend/src/components/visual_components/ElectricCar2.jsx, frontend/src/components/visual_components/Freezer.jsx, frontend/src/components/visual_components/HeatPump.jsx, frontend/src/components/visual_components/Heater.jsx, frontend/src/components/visual_components/HotWaterHeater.jsx, frontend/src/components/visual_components/Jacuzzi.jsx, frontend/src/components/visual_components/SolarPanel1.jsx, frontend/src/components/visual_components/SolarPanel2.jsx, frontend/src/components/visual_components/SolarPanel3.jsx, frontend/src/components/visual_components/SolarPanel4.jsx, frontend/src/components/visual_components/Stove.jsx, frontend/src/components/visual_components/WashingMachine.jsx
- Korjattu komponenttien sivuilla olevat kuvaajat alkamaan aina samasta ajasta kuin demo
- Poistettu optimointi niiltä komponenteilta, joita ei haluta optimoida
- Komponenttisivujen tekstiä muutettu sen mukaisesti, esittääkö demo mennyttä vai tulevaa aikaa
- Kuvaajien värejä muutettu demon värimaailmaan sopivammaksi
=> charts start at demo time & unnecessary optimizations removed

frontend/src/components/Demo.jsx, frontend/src/components/DemoClock.jsx, frontend/src/components/EnergyComponent.jsx, frontend/src/components/EnergyComponentPage.jsx, frontend/src/components/visual_components/ElectricBoard.jsx, frontend/src/components/visual_components/ElectricCar1.jsx, frontend/src/components/visual_components/ElectricCar2.jsx, frontend/src/components/visual_components/Freezer.jsx, frontend/src/components/visual_components/HeatPump.jsx, frontend/src/components/visual_components/Heater.jsx, frontend/src/components/visual_components/HotWaterHeater.jsx, frontend/src/components/visual_components/Jacuzzi.jsx, frontend/src/components/visual_components/Optimizer.jsx, frontend/src/components/visual_components/SolarPanel1.jsx, frontend/src/components/visual_components/SolarPanel2.jsx, frontend/src/components/visual_components/SolarPanel3.jsx, frontend/src/components/visual_components/SolarPanel4.jsx, frontend/src/components/visual_components/Stove.jsx, frontend/src/components/visual_components/WashingMachine.jsx
Optimoijakomponentti toimii nyt niin, että demon ollessa käynnissä optimoijakomponentin päällä näytetään sekunnin ajan download-kuvaketta ja optimoijan infolaatikossa teksti joka kertoo, että optimoija lataa tietoja internetistä. Tämän jälkeen sekunnin ajan optimoijakomponentin päällä näkyy upload-kuvake ja optimoitavien komponenttien päällä download-kuvake, ja infolaatikossa teksti että optimoijakomponentti siirtää tietoja muille komponenteille. Tämän jälkeen optimoijakomponentin infolaatikossa näkyy kolmen sekunnin ajan "lähtölaskenta" seuraavaan tietojen lataukseen. Lisätty myös optimoijakomponentin sivulle hintatiedot tekstimuodossa ja kunkin tuntihinnan kohdalle hinnan lähde/tyyppi. (Muutosehdotuksia esim. animaation nopeuteen, optimoijakomponentin sivun sisältöön tai tietojen …
=> Optimizer functionality

frontend/src/components/Demo.jsx, frontend/src/components/DemoClock.jsx, frontend/src/components/EnergyComponent.jsx, frontend/src/components/EnergyComponentPage.jsx, frontend/src/components/Instructions.jsx, frontend/src/components/visual_components/ElectricBoard.jsx, frontend/src/components/visual_components/ElectricCar1.jsx, frontend/src/components/visual_components/ElectricCar2.jsx, frontend/src/components/visual_components/Freezer.jsx, frontend/src/components/visual_components/HeatPump.jsx, frontend/src/components/visual_components/Heater.jsx, frontend/src/components/visual_components/HotWaterHeater.jsx, frontend/src/components/visual_components/Jacuzzi.jsx, frontend/src/components/visual_components/Optimizer.jsx, frontend/src/components/visual_components/SolarPanel1.jsx, frontend/src/components/visual_components/SolarPanel2.jsx, frontend/src/components/visual_components/SolarPanel3.jsx, frontend/src/components/visual_components/SolarPanel4.jsx, frontend/src/components/visual_components/Stove.jsx, frontend/src/components/visual_components/WashingMachine.jsx, frontend/src/theme.js
Tallennustilana käytetään localstoragen sijasta sessionstoragea (paitsi demoTime, demoPassedHours ja demoStartTime -muuttujiin tai komponenttien näkyvyyden määrittäviin muuttujiin en ole koskenut, olisiko parempi vaihtaa nekin sessionStorageen?)
Lisäksi energiakomponenttien reunan läpinäkyvyysarvot on nyt myös tallennettu sessionstorageen eli säilyy kun poistuu pääsivulta ja palaa takaisin.
Sain myös ratkaistua ongelman miksi optimointianimaatio ei aina toiminut, se johtui siitä että jos demon nopeutta ei muuttanut, niin speed-muuttujan arvoa ei tallennettu sessionstorageen, vaan ainoastaan DemoClock-komponentin omaan speed-muuttujaan, jolloin Demo-komponentti ei sitä pystynyt sessionstoragesta lukemaan ja määrittämäään timeLeft-muuttujaa josta download, upload ja nextDownloadIn …
=> Save data to sessionstorage

frontend/src/components/Demo.jsx, frontend/src/components/DemoClock.jsx, frontend/src/components/ElectricityPrice.jsx, frontend/src/components/RealtimeClock.jsx
Checkboxien värit muutettu. Aika- ja kaavioboxien ulkonäköä hiottu yksinkertaisemmaksi ja selkeämmäksi.
=> Updated checkboxes

docs/structure.md
Dokumentaatio frontendin rakenteesta.
=> Add structure documentation
